packages:
  boost:
    version: [1.66.0]
  cmake:
    version: [3.9.4]
  netcdf:
    version: [4.4.1.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.1]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  yaml-cpp:
    version: [develop]
  openmpi:
    version: [1.10.4]
  netlib-lapack:
    version: [3.8.0]
  python:
    paths:
      python@2.7.10: /usr
    buildable: False
  all:
    variants: build_type=Release
    providers:
      mpi: [openmpi@1.10.4]
      blas: [netlib-lapack@3.8.0]
      lapack: [netlib-lapack@3.8.0]
