packages:
  py-matplotlib:
    version: [2.0.2]
  m4:
    version: [1.4.18]
  cmake:
    version: [3.9.4]
  boost:
    version: [1.66.0]
  netcdf:
    version: [4.4.1.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.1]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.0.1]
    variants: fabrics=psm2
  intel-mpi:
    version: [2017.2.174]
  intel-mkl:
    version: [2017.2.174]
  yaml-cpp:
    version: [develop]
  netlib-lapack:
    version: [3.8.0]
  all:
    compiler: [gcc@4.9.2, intel@17.0.2]
    variants: build_type=Release
    providers:
      mpi: [openmpi, intel-mpi@2017.2.174]
      blas: [netlib-lapack, intel-mkl@2017.2.174]
      lapack: [netlib-lapack, intel-mkl@2017.2.174]
