packages:
  cmake:
    version: [3.12.2]
  boost:
    version: [1.68.0]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.3]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.2]
    variants: fabrics=psm2
  openfast:
    version: [develop]
  intel-mpi:
    version: [2017.2.174]
  intel-mkl:
    version: [2017.2.174]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  all:
    compiler: [gcc@4.9.2, intel@17.0.2]
    # Spack uses build_type=RelWithDebInfo by default for CMake packages
    # and creates huge binaries unless you do this:
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.2, intel-mpi@2017.2.174]
      blas: [netlib-lapack@3.8.0, intel-mkl@2017.2.174]
      lapack: [netlib-lapack@3.8.0, intel-mkl@2017.2.174]
