packages:
  all:
    compiler:
    - gcc
    - intel
    modules: {}
    paths: {}
    providers:
      blas:
      - netlib-lapack
      lapack:
      - netlib-lapack
      mpi:
      - mpich
    version: []
    variants: +mpi build_type=Release
  mpich:
    version: [7.6.2]
    buildable: false
    modules:
        mpich@7.6.2: cray-mpich
    paths: {}
    providers: {}
    compiler: []
  boost:
    version: [1.60.0]
  hdf5:
      version: [1.8.16]
      variants: +cxx+mpi+hl
      buildable: false
      modules:
          hdf5@1.8.16+cxx+mpi+hl: cray-hdf5-parallel/1.8.16
  netcdf:
      version: [4.3.3.1]
      variants: maxdims=65536 maxvars=524288
  superlu:
    version: [4.3]
  openfast:
    version: [develop]
  parallel-netcdf:
      version: [1.6.1]
  intel-mkl:
      version: [17.0.2.174]
      buildable: false
      paths:
          intel-mkl@17.0.2.174: /opt/intel/2017.2.028/compilers_and_libraries_2017.2.174/linux/mkl
  cmake:
      version: [3.9.0]
      buildable: false
      modules:
          cmake@3.9.0: cmake/3.9.0
  yaml-cpp:
      version: [0.6.2]
