packages:
    binutils:
        version: [2.29.1]
    mpich:
        modules:
            mpich@7.7.0: cray-mpich/7.7.0
        buildable: False
    boost:
        paths:
            boost@1.64.0 %intel: /soft/libraries/boost/1.64.0/intel
            boost@1.64.0 %gcc: /soft/libraries/boost/1.64.0/gnu
        buildable: False
    python:
        paths:
            python@2.7.13: /usr
        buildable: False
    cmake:
        version: [3.9.1]
        paths:
            cmake@3.9.1: /soft/buildtools/cmake/3.9.1
        buildable: False
    hdf5:
        version: [1.10.1]
        variants: +cxx+mpi+hl
        buildable: false
        modules:
            hdf5@1.10.1+cxx+mpi+hl: cray-hdf5/1.10.1.1
    netcdf:
        version: [4.4.1.1]
        buildable: false
        modules:
            netcdf@4.4.1.1+mpi+parallel-netcdf: cray-netcdf-hdf5parallel/4.4.1.1.6
        variants: maxdims=65536 maxvars=524288
    superlu:
      version: [4.3]
    openfast:
      version: [develop]
    yaml-cpp:
      version: [0.6.2]
    netlib-lapack:
        version: [3.6.1]
        buildable: False
        paths:
            netlib-lapack@3.6.1: /usr
    bzip2:
        version: [1.0.6]
        buildable: False
        paths:
            bzip2@1.0.6: /usr
    zlib:
        version: [1.2.8]
        buildable: False
        paths:
            zlib@1.2.8: /usr
    parallel-netcdf:
        version: [1.8.0]
        buildable: false
        modules:
            parallel-netcdf@1.8.0: cray-parallel-netcdf/1.8.1.3
    all:
      compiler: [intel@18.2.199, gcc@7.3.0]
      variants: +mpi build_type=Release
      providers:
        mpi: [mpich@7.7.0]
        blas: [netlib-lapack@3.6.1]
        lapack: [netlib-lapack@3.6.1]
