packages:
    mpich:
        modules:
            mpich@7.7.0%gcc@5.3.0 arch=cray-CNL-mic_knl: cray-mpich/7.7.0
        buildable: False
    python:
        paths:
            python@2.7.13%gcc@5.3.0 arch=cray-CNL-mic_knl: /usr
            python@2.7.13%intel@16.0.3.210 arch=cray-CNL-mic_knl: /usr
        buildable: False
    boost:
      version: [1.66.0]
    cmake:
      version: [3.9.4]
    hdf5:
        version: [1.10.1]
        variants: +cxx+mpi+hl
        buildable: false
        modules:
            hdf5@1.10.1+cxx+mpi+hl: cray-hdf5/1.10.1.1
    netcdf:
        version: [4.4.1.1]
        buildable: false
        modules:
            netcdf@4.4.1.1+mpi+parallel-netcdf: cray-netcdf-hdf5parallel/4.4.1.1.6
        variants: maxdims=65536 maxvars=524288
    superlu:
      version: [4.3]
    openfast:
      version: [develop]
    yaml-cpp:
      version: [0.6.2]
    netlib-lapack:
        version: [3.6.1]
        buildable: False
        paths:
            netlib-lapack@3.6.1: /usr
    parallel-netcdf:
        version: [1.8.0]
        buildable: false
        modules:
            parallel-netcdf@1.8.0: cray-parallel-netcdf/1.8.1.3
    all:
      compiler: [gcc@7.3.0]
      variants: +mpi build_type=Release
      providers:
        mpi: [mpich@7.7.0]
        blas: [netlib-lapack@3.6.1]
        lapack: [netlib-lapack@3.6.1]
