compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran-7
      fc: /usr/local/bin/gfortran-7
    spec: clang@9.0.0-apple
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-7
      cxx: /usr/local/bin/g++-7
      f77: /usr/local/bin/gfortran-7
      fc: /usr/local/bin/gfortran-7
    spec: gcc@7.3.0
    target: x86_64
