packages:
  binutils:
    version: [2.29.1]
  cmake:
    paths:
      cmake@3.14.0: /usr/local/Cellar/cmake/3.14.0
    buildable: False
  pkg-config:
    paths:
      pkg-config@0.29.2: /usr/local/Cellar/pkg-config/0.29.2
    buildable: False
  python:
    paths:
      python@2.7.10: /usr
    buildable: False
  libxml2:
    version: [2.9.8]
  boost:
    version: [1.68.0]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.4]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.3]
  openfast:
    version: [develop]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  all:
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.3]
      blas: [netlib-lapack@3.8.0]
      lapack: [netlib-lapack@3.8.0]
