packages:
  cmake:
    paths:
      cmake@3.9.3 arch=darwin-sierra-x86_64: /usr/local/Cellar/cmake/3.9.3_1
    buildable: False
  pkg-config:
    paths:
      pkg-config@0.29.2 arch=darwin-sierra-x86_64: /usr/local/Cellar/pkg-config/0.29.2
    buildable: False
  python:
    paths:
      python@2.7.10: /usr
    buildable: False
  boost:
    version: [1.66.0]
  netcdf:
    version: [4.4.1.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.1]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.0.1]
  yaml-cpp:
    version: [develop]
  netlib-lapack:
    version: [3.8.0]
  all:
    variants: build_type=Release
    providers:
      mpi: [openmpi]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
