packages:
  cmake:
    paths:
      cmake@3.11.0: /usr/local/Cellar/cmake/3.11.0
    buildable: False
  pkg-config:
    paths:
      pkg-config@0.29.2: /usr/local/Cellar/pkg-config/0.29.2
    buildable: False
  m4:
    paths:
      m4@1.4.6: /usr
    buildable: False
  python:
    paths:
      python@2.7.10: /usr
    buildable: False
  boost:
    version: [1.60.0]
  netcdf:
    version: [4.3.3.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.6.1]
  hdf5:
    version: [1.8.16]
    variants: +cxx
  superlu:
    version: [4.3]
  openmpi:
    version: [1.10.4]
  yaml-cpp:
    version: [develop]
  netlib-lapack:
    version: [3.6.1]
  all:
    variants: build_type=Release
    providers:
      mpi: [openmpi@1.10.4]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
