packages:
  all:
    compiler:
    - gcc
    - intel
    modules: {}
    paths: {}
    providers:
      blas:
      - netlib-lapack
      lapack:
      - netlib-lapack
      mpi:
      - mpich
    version: []
    variants: +mpi build_type=Release
  mpich:
    version: [7.7.0]
    buildable: false
    modules:
        mpich@7.7.0: cray-mpich
    paths: {}
    providers: {}
    compiler: []
  boost:
      version: [1.68.0]
  hdf5:
      version: [1.10.3]
      variants: +cxx+mpi+hl
  netcdf:
      version: [4.6.1]
  superlu:
      version: [4.3]
  parallel-netcdf:
      version: [1.8.0]
  netlib-lapack:
      version: [3.8.0]
  cmake:
      version: [3.12.2]
  yaml-cpp:
      version: [0.6.2]
