packages:
  all:
    compiler:
    - gcc
    - intel
    modules: {}
    paths: {}
    providers:
      blas:
      - netlib-lapack
      lapack:
      - netlib-lapack
      mpi:
      - mpich
    version: []
    variants: +mpi build_type=Release
  mpich:
    version: [7.6.2]
    buildable: false
    modules:
        mpich@7.6.2: cray-mpich
    paths: {}
    providers: {}
    compiler: []
  boost:
      version: [1.60.0]
  #    buildable: false
  #    modules:
  #        boost@1.63.0: boost/1.63
  hdf5:
      version: [1.10.1]
      variants: +cxx+mpi+hl
      buildable: false
      paths:
          hdf5@1.10.1+cxx+mpi+hl%gcc@4.9.3: /opt/cray/pe/hdf5/1.10.1.1/gnu/4.9
  netcdf:
      buildable: false
      modules:
          netcdf@4.4.1.1+mpi+parallel-netcdf: cray-netcdf-hdf5parallel/4.4.1.1.3
  superlu:
    version: [4.3]
  parallel-netcdf:
      version: [1.8.0]
      buildable: false
      modules:
          parallel-netcdf@1.8.0: cray-parallel-netcdf/1.8.1.3
  zlib:
      version: [1.2.8]
      buildable: false
      modules:
          zlib@1.2.8: zlib/1.2.8
  intel-mkl:
      version: [17.0.2.174]
      buildable: false
      paths:
          intel-mkl@17.0.2.174: /opt/intel/compilers_and_libraries_2017.2.174/linux/mkl
  netlib-lapack:
      version: [3.6.1]
      buildable: False
      paths:
          netlib-lapack@3.6.1: /usr
  openssl:
      version: [1.0.1i]
      buildable: False
      paths:
          openssl@1.0.1i: /usr
  cmake:
      version: [3.8.2]
      buildable: False
      paths:
          cmake@3.8.2: /usr/common/software/cmake/3.8.2
  bzip2:
      version: [1.0.6]
      buildable: False
      paths:
          bzip2@1.0.6: /usr
  yaml-cpp:
      version: [0.5.3]
