packages:
  all:
    compiler:
    - gcc
    - intel
    modules: {}
    paths: {}
    providers:
      blas:
      - netlib-lapack
      lapack:
      - netlib-lapack
      mpi:
      - mpich
    version: []
    variants: +mpi build_type=Release
  mpich:
    version: [7.6.2]
    buildable: false
    modules:
        mpich@7.6.2: cray-mpich
    paths: {}
    providers: {}
    compiler: []
  boost:
      version: [1.60.0]
  hdf5:
      version: [1.8.16]
      variants: +cxx+mpi+hl
  netcdf:
      version: [4.3.3.1]
  superlu:
    version: [4.3]
  parallel-netcdf:
      version: [1.6.1]
  zlib:
      version: [1.2.8]
  intel-mkl:
      version: [17.0.2.174]
      buildable: false
      paths:
          intel-mkl@17.0.2.174: /opt/intel/compilers_and_libraries_2017.2.174/linux/mkl
  netlib-lapack:
      version: [3.6.1]
  cmake:
      version: [3.8.2]
      buildable: False
      paths:
          cmake@3.8.2: /usr/common/software/cmake/3.8.2
  bzip2:
      version: [1.0.6]
  yaml-cpp:
      version: [0.5.3]
