compilers:
- compiler:
    environment: {}
    extra_rpaths:
     - /soft/compilers/ibmcmp-may2016/xlf/bg/14.1/lib
     - /soft/compilers/ibmcmp-may2016/xlf/bg/14.1/lib64
     - /soft/compilers/ibmcmp-may2016/vac/bg/12.1/lib
     - /soft/compilers/ibmcmp-may2016/vac/bg/12.1/lib64
     - /soft/compilers/ibmcmp-may2016/vacpp/bg/12.1/lib
     - /soft/compilers/ibmcmp-may2016/vacpp/bg/12.1/lib64
    flags:
      fflags: -qzerosize
    modules: []
    operating_system: cnk
    paths:
      cc: /soft/compilers/ibmcmp-may2016/vac/bg/12.1/bin/xlc
      cxx: /soft/compilers/ibmcmp-may2016/vacpp/bg/12.1/bin/xlC
      f77: /soft/compilers/ibmcmp-may2016/xlf/bg/14.1/bin/xlf
      fc: /soft/compilers/ibmcmp-may2016/xlf/bg/14.1/bin/xlf2003
    spec: xl@12.1
    target: ppc64
- compiler:
    environment: {}
    extra_rpaths:
     - /soft/compilers/gcc/4.8.4/powerpc64-bgq-linux/lib
     - /soft/compilers/gcc/4.8.4/lib/gcc/powerpc64-bgq-linux/4.8.4
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
    modules: []
    operating_system: cnk
    paths:
      cc: /soft/compilers/gcc/4.8.4/bin/powerpc64-bgq-linux-gcc
      cxx: /soft/compilers/gcc/4.8.4/bin/powerpc64-bgq-linux-g++
      f77: /soft/compilers/gcc/4.8.4/bin/powerpc64-bgq-linux-gfortran
      fc: /soft/compilers/gcc/4.8.4/bin/powerpc64-bgq-linux-gfortran
    spec: gcc@4.8.4
    target: ppc64
