packages:
    libxml2:
        version: [2.9.4]
    yaml-cpp:
        version: [0.6.2]
    hdf5:
        paths:
            hdf5@1.10.0%gcc: /soft/libraries/hdf5/current/cnk-gcc/current
        buildable: False
        variants: +cxx+hl
        version: [1.10.0]
    superlu:
        version: [4.3]
    #parallel-netcdf:
    #    paths: 
    #        parallel-netcdf@1.6.1%gcc: /soft/libraries/pnetcdf/1.6.1/cnk-gcc/current
    #    buildable: False
    #    version: [1.8.0]
    #netcdf:
    #    paths: 
    #        netcdf@4.3.3.1%gcc: /soft/libraries/netcdf/4.3.3-f4.4.1/cnk-gcc/current
    #    variants: ~dap~hdf4 maxdims=1024 maxvars=8192 +mpi+parallel-netcdf+shared
    #    version: [4.3.3.1]
    parallel-netcdf:
        version: [1.8.0]
    netcdf:
        variants: maxdims=65536 maxvars=524288 +mpi+parallel-netcdf
        version: [4.4.1.1]
    boost:
        paths:
            boost@1.60.0%gcc: /soft/libraries/boost/1.60.0/cnk-gcc/current
        buildable: False
        version: [1.60.0]
    zlib:
        paths:
            zlib@1.2.8%gcc: /soft/libraries/alcf/current/gcc/ZLIB
        buildable: False
        version: [1.2.8]
    mpich:
        paths:
            mpich@3.2%gcc: /soft/libraries/mpich3/gcc.ndebug
        buildable: False
        version: [3.2]
    cmake:
        paths:
            cmake@3.8.1: /soft/buildtools/cmake/3.8.1
        buildable: False
        version: [3.8.1]
    python:
        paths:
            python@2.7.9: /soft/interpreters/python-2.7.9/powerpc64-bgq-linux
        version: [2.7.9]
        buildable: False
    netlib-lapack:
        paths:
            netlib-lapack@3.6.1%gcc: /soft/libraries/alcf/current/gcc/BLAS
        buildable: False
        version: [3.6.1]
    all:
        compiler: [gcc@4.8.4]
        variants: ~shared +mpi build_type=Release
        providers:
            mpi: [mpich]
            blas: [netlib-lapack]
            lapack: [netlib-lapack]
