packages:
    yaml-cpp:
        version: [0.5.3]
    hdf5:
        paths:
            hdf5@1.8.17%gcc: /soft/libraries/hdf5/1.8.17/cnk-gcc/current
        buildable: False
        variants: +cxx+hl
        version: [1.8.17]
    superlu:
        version: [4.3]
    parallel-netcdf:
        paths: 
            parallel-netcdf@1.6.1%gcc: /soft/libraries/pnetcdf/1.6.1/cnk-gcc/current
        buildable: False
        version: [1.6.1]
    netcdf:
        paths: 
            netcdf@4.3.3.1%gcc: /soft/libraries/netcdf/4.3.3-f4.4.1/cnk-gcc/current
        variants: ~dap~hdf4 maxdims=1024 maxvars=8192 +mpi+parallel-netcdf+shared
        version: [4.3.3.1]
    boost:
        paths:
            boost@1.60.0%gcc: /soft/libraries/boost/1.60.0/cnk-gcc/current
        buildable: False
        version: [1.60.0]
    mpich:
        paths:
            mpich@3.2%gcc: /soft/libraries/mpich3/gcc
        buildable: False
        version: [3.2]
    autoconf:
        paths:
            autoconf@system: /usr
        buildable: False
        version: [system]
    automake:
        paths:
            automake@system: /usr
        buildable: False
        version: [system]
    pkg-config:
        paths:
            pkg-config@0.23: /usr
        buildable: False
        version: [0.23]
    flex:
        paths:
            flex@system: /usr
        buildable: False
        version: [system]
    bison:
        paths:
            bison@system: /usr
        buildable: False
        version: [system]
    ncurses:
        paths:
            ncurses@system: /usr
        buildable: False
        version: [system]
    libtool:
        paths:
            libtool@system: /usr
        buildable: False
        version: [system]
    bzip2:
        paths:
            bzip2@system: /usr
        buildable: False
        version: [system]
    xz:
        paths:
            xz@system: /usr
        buildable: False
    cmake:
        paths:
            cmake@3.8.1: /soft/buildtools/cmake/3.8.1
        buildable: False
        version: [3.8.1]
    python:
        paths:
            python@2.7.9: /soft/interpreters/python-2.7.9/powerpc64-bgq-linux
        version: [2.7.9]
        buildable: False
    zlib:
        paths:
            zlib@1.2.7%gcc: /soft/libraries/alcf/current/gcc/ZLIB
        buildable: False
        version: [1.2.7]
    netlib-lapack:
        paths:
            netlib-lapack@3.6.1%gcc: /soft/libraries/alcf/current/gcc/BLAS
        buildable: False
        version: [3.6.1]
    all:
        compiler: [gcc@4.8.4]
        variants: ~shared build_type=Release
        providers:
            mpi: [mpich]
            blas: [netlib-lapack]
            lapack: [netlib-lapack]
