modules:
  enable:
    - tcl
  prefix_inspections:
    bin:
      - PATH
    man:
      - MANPATH
    share/man:
      - MANPATH
    share/aclocal:
      - ACLOCAL_PATH
    lib:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    lib64:
      - LIBRARY_PATH
      - LD_LIBRARY_PATH
    include:
      - CPATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    naming_scheme: '${PACKAGE}/${VERSION}/${COMPILERNAME}-${COMPILERVER}'
    hash_length: 0
    all:
      suffixes:
        hdf5+mpi: 'mpi'
      conflict:
        - '${PACKAGE}'
      environment:
        set:
          '${PACKAGE}_ROOT_DIR': '${PREFIX}'
    whitelist: ['boost', 'cmake', 'gcc', 'hdf5', 'intel-mkl', 'intel-mpi', 'lammps', 'netcdf', 'openmpi']
    blacklist: ['autoconf', 'automake', 'bzip2', 'diffutils', 'environment-modules', 'gdbm', 'gmp', 'hwloc', 'libpciaccess', 'libsigsegv', 'isl', 'libtool', 'libxml2', 'm4', 'mpc', 'mpfr', 'ncurses', 'numactl', 'openssl', 'pcre', 'perl', 'pkgconf', 'python', 'readline', 'sqlite', 'util-macros', 'xz', 'zlib']
