packages:
  binutils:
    version: [2.29.1]
  cmake:
    paths:
      cmake@3.12.3: /nopt/nrel/apps/compilers/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cmake-3.12.3-qd2xkvdfpka7dsq46omrtp6xo25ffqtf
    buildable: False
  netcdf:
    variants: maxdims=65536 maxvars=524288
  hdf5:
    variants: +cxx+hl
  openmpi:
    version: [3.1.3]
    variants: fabrics=verbs schedulers=slurm
  intel-mpi:
    version: [2018.3.222]
  intel-mkl:
    version: [2018.3.222]
  all:
    compiler: [gcc@7.3.0, intel@18.0.3]
    # Spack uses build_type=RelWithDebInfo by default for CMake packages
    # and creates huge binaries unless you do this:
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.3, intel-mpi@2018.3.222]
      blas: [netlib-lapack@3.8.0, intel-mkl@2018.3.222]
      lapack: [netlib-lapack@3.8.0, intel-mkl@2018.3.222]
