packages:
  libxml2:
    version: [2.9.8]
  boost:
    version: [1.68.0]
  netcdf:
    version: [4.6.3]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.1]
  mesa:
    variants: swr=skx
  hdf5:
    version: [1.10.5]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  slurm:
    paths:
      slurm@18.08.3: /nopt/slurm/current
    buildable: False
  cuda:
    paths:
      cuda@10.0.130: /nopt/nrel/apps/cuda/10.0.130
      cuda@9.2.88: /nopt/nrel/apps/cuda/9.2.88
    buildable: False
  openmpi:
    version: [3.1.4]
    variants: +pmi +cuda fabrics=verbs schedulers=slurm
  mpich:
    version: [3.3]
    variants: netmod=mxm +hydra +slurm
  hwloc:
    variants: +cuda ~nvml ~gl
  openfast:
    version: [develop]
  intel-mpi:
    version: [2018.4.274]
  intel-mkl:
    version: [2018.4.274]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  py-matplotlib:
    version: [2.2.3]
  fftw:
    variants: +mpi+fma simd=avx512
  trilinos:
    variants: ~python~complex+explicit_template_instantiation~float~fortran~openmp+shared~xsdkflags+boost~cgns+exodus+gtest+hdf5~hypre~metis~mumps+pnetcdf~suite-sparse~superlu-dist+superlu~x11+zlib~alloptpkgs~amesos+amesos2~anasazi~aztec+belos~epetra~epetraext~ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos~ml~minitensor+muelu~nox~piro~phalanx~rol~rythmos~sacado~shylu+stk+shards~teko~tempus+teuchos+tpetra+zoltan+zoltan2~dtk~fortrilinos
  all:
    compiler: [gcc@7.4.0, intel@18.0.4]
    # Spack uses build_type=RelWithDebInfo by default for CMake packages
    # and creates huge binaries unless you do this:
    variants: build_type=Release
    providers:
      mpi: [mpich@3.3, intel-mpi@2018.4.274]
      blas: [netlib-lapack@3.8.0, intel-mkl@2018.4.274]
      lapack: [netlib-lapack@3.8.0, intel-mkl@2018.1.163]
