packages:
  binutils:
    version: [2.29.1]
  libxml2:
    version: [2.9.8]
    variants: +python
  glib:
    version: [2.55.1]
  m4:
    version: [1.4.18]
  boost:
    version: [1.68.0]
  cmake:
    version: [3.12.3]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.3]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.2]
    variants: fabrics=verbs schedulers=tm
  openfast:
    version: [develop]
  intel-mpi:
    version: [2018.1.163]
  intel-mkl:
    version: [2018.1.163]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  all:
    compiler: [gcc@6.2.0, intel@18.1.163]
    # Spack uses build_type=RelWithDebInfo by default for CMake packages
    # and creates huge binaries unless you do this:
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.2, intel-mpi@2018.1.163]
      blas: [netlib-lapack@3.8.0, intel-mkl@2018.1.163]
      lapack: [netlib-lapack@3.8.0, intel-mkl@2018.1.163]
