compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
      fcflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    extra_rpaths:
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/lib/gcc/x86_64-unknown-linux-gnu/4.9.4
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/libexec/gcc/x86_64-unknown-linux-gnu/4.9.4
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/lib64
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
      fcflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/bin/gcc
      cxx: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/bin/g++
      f77: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/bin/gfortran
      fc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-4.9.4-3gd7wz5gvtdf35u3j56ill4n45uk7smr/bin/gfortran
    spec: gcc@4.9.4
    target: x86_64
- compiler:
    extra_rpaths:
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/lib/gcc/x86_64-unknown-linux-gnu/5.5.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/lib64
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
      fcflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/bin/gcc
      cxx: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/bin/g++
      f77: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/bin/gfortran
      fc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.5.0-pahakkxrnhn63pwol65a3oaqrbunlv4a/bin/gfortran
    spec: gcc@5.5.0
    target: x86_64
- compiler:
    extra_rpaths:
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/lib/gcc/x86_64-unknown-linux-gnu/6.4.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/libexec/gcc/x86_64-unknown-linux-gnu/6.4.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/lib64
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
      fcflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/bin/gcc
      cxx: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/bin/g++
      f77: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/bin/gfortran
      fc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/bin/gfortran
    spec: gcc@6.4.0
    target: x86_64
- compiler:
    extra_rpaths:
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/lib/gcc/x86_64-unknown-linux-gnu/7.3.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/libexec/gcc/x86_64-unknown-linux-gnu/7.3.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/lib64
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
      fcflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/bin/gcc
      cxx: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/bin/g++
      f77: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/bin/gfortran
      fc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-ewgozmxdrcyfpa6hxjis7bm6kcwk2pzh/bin/gfortran
    spec: gcc@7.3.0
    target: x86_64
- compiler:
    environment:
      set:
        INTEL_LICENSE_FILE: 28518@hpc-admin1.hpc.nrel.gov
    extra_rpaths:
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2018.1-bfdqgk5ngxudy6nga65k374zouwp2suh/compilers_and_libraries/linux/lib/intel64
    flags:
      cflags: -O2 -xCORE-AVX2
      cxxflags: -O2 -xCORE-AVX2
      fflags: -O2 -xCORE-AVX2
      fcflags: -O2 -xCORE-AVX2
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2018.1-bfdqgk5ngxudy6nga65k374zouwp2suh/compilers_and_libraries/linux/bin/intel64/icc
      cxx: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2018.1-bfdqgk5ngxudy6nga65k374zouwp2suh/compilers_and_libraries/linux/bin/intel64/icpc
      f77: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2018.1-bfdqgk5ngxudy6nga65k374zouwp2suh/compilers_and_libraries/linux/bin/intel64/ifort
      fc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2018.1-bfdqgk5ngxudy6nga65k374zouwp2suh/compilers_and_libraries/linux/bin/intel64/ifort
    spec: intel@18.1.163
    target: x86_64
- compiler:
    extra_rpaths:
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-6.0.0-xxji3hq27n7zpibeew6vhlyvayptzoks/lib
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-6.0.0-xxji3hq27n7zpibeew6vhlyvayptzoks/lib/clang/6.0.0/lib/linux
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/lib/gcc/x86_64-unknown-linux-gnu/6.4.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/libexec/gcc/x86_64-unknown-linux-gnu/6.4.0
     - /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/lib64
    flags:
      cflags: -O2
      cxxflags: -O2
      fflags: -O2
      fcflags: -O2
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-6.0.0-xxji3hq27n7zpibeew6vhlyvayptzoks/bin/clang
      cxx: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-6.0.0-xxji3hq27n7zpibeew6vhlyvayptzoks/bin/clang++
      f77: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/bin/gfortran
      fc: /opt/software/b/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-yyzc7g6v43jb3jcbr4lbcxnnbuap3lbq/bin/gfortran
    spec: clang@6.0.0
    target: x86_64
