packages:
  m4:
    version: [1.4.18]
  cmake:
    version: [3.11.1]
  boost:
    version: [1.66.0]
  netcdf:
    version: [4.4.1.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.1]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.0.1]
  intel-mpi:
    version: [2018.1.163]
  intel-mkl:
    version: [2018.1.163]
  yaml-cpp:
    version: [develop]
  netlib-lapack:
    version: [3.8.0]
  all:
    compiler: [gcc@4.9.4, gcc@5.5.0, gcc@6.4.0, gcc@7.3.0, intel@18.0.1]
    variants: build_type=Release
    providers:
      mpi: [openmpi, intel-mpi@2018.1.163]
      blas: [netlib-lapack, intel-mkl@2018.1.163]
      lapack: [netlib-lapack, intel-mkl@2018.1.163]
