packages:
  libxml2:
    version: [2.9.8]
    variants: +python
  cmake:
    version: [3.12.2]
  boost:
    version: [1.68.0]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.3]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.2]
  openfast:
    version: [develop]
  intel-mpi:
    version: [2018.1.163]
  intel-mkl:
    version: [2018.1.163]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  py-matplotlib:
    version: [2.2.3]
  all:
    compiler: [gcc@4.8.5, gcc@4.9.4, gcc@5.5.0, gcc@6.4.0, gcc@7.3.0, gcc@8.1.0, clang@6.0.0, intel@18.1.163]
    # Spack uses build_type=RelWithDebInfo by default for CMake packages
    # and creates huge binaries unless you do this:
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.2, intel-mpi@2018.1.163]
      blas: [netlib-lapack@3.8.0, intel-mkl@2018.1.163]
      lapack: [netlib-lapack@3.8.0, intel-mkl@2018.1.163]
