packages:
  libxml2:
    version: [2.9.8]
  binutils:
    version: [2.29.1]
  cmake:
    version: [3.13.4]
  mesa:
    variants: swr=avx2
  boost:
    version: [1.68.0]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.4]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.4]
  openfast:
    version: [develop]
  intel-mpi:
    version: [2018.4.274]
  intel-mkl:
    version: [2018.4.274]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  py-matplotlib:
    version: [2.2.3]
  fftw:
    variants: +mpi+fma simd=avx2
  trilinos:
    variants: ~python~complex+explicit_template_instantiation~float~fortran~openmp+shared~xsdkflags+boost~cgns+exodus+gtest+hdf5~hypre~metis~mumps+pnetcdf~suite-sparse~superlu-dist+superlu~x11+zlib~alloptpkgs~amesos+amesos2~anasazi~aztec+belos~epetra~epetraext~ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos~ml~minitensor+muelu~nox~piro~phalanx~rol~rythmos~sacado~shylu+stk+shards~teko~tempus+teuchos+tpetra+zoltan+zoltan2~dtk~fortrilinos
  all:
    compiler: [gcc, clang, intel]
    variants: build_type=Release
    providers:
      mpi: [openmpi, intel-mpi]
      blas: [netlib-lapack, intel-mkl]
      lapack: [netlib-lapack, intel-mkl]
