packages:
  libxml2:
    version: [2.9.8]
  freetype:
    version: [2.7.1]
  binutils:
    version: [2.29.1]
  boost:
    version: [1.68.0]
  netcdf:
    version: [4.6.1]
    variants: maxdims=65536 maxvars=524288
  parallel-netcdf:
    version: [1.8.0]
  hdf5:
    version: [1.10.4]
    variants: +cxx+hl
  superlu:
    version: [4.3]
  openmpi:
    version: [3.1.4]
  openfast:
    version: [develop]
  intel-mpi:
    version: [2018.4.274]
  intel-mkl:
    version: [2018.4.274]
  yaml-cpp:
    version: [0.6.2]
  netlib-lapack:
    version: [3.8.0]
  py-matplotlib:
    version: [2.2.3]
  fftw:
    variants: +mpi+fma simd=avx2
  all:
    compiler: [gcc@4.8.5, gcc@4.9.4, gcc@5.5.0, gcc@6.4.0, gcc@7.3.0, gcc@8.2.0, clang@7.0.0, intel@18.0.4]
    variants: build_type=Release
    providers:
      mpi: [openmpi@3.1.3, intel-mpi@2018.4.274]
      blas: [netlib-lapack@3.8.0, intel-mkl@s2018.4.274]
      lapack: [netlib-lapack@3.8.0, intel-mkl@2018.4.274]
